// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Webbanhang.Models;

#nullable disable

namespace Webbanhang.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260606090000_AddAvatarAndOrderUserId")]
    partial class AddAvatarAndOrderUserId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // Model snapshot is maintained by ApplicationDbContextModelSnapshot.
            // This minimal designer file supplies the migration metadata needed by EF Core.
#pragma warning restore 612, 618
        }
    }
}
